apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"auth-service"},"name":"auth-service","namespace":"togglemaster"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"auth-service"}},"template":{"metadata":{"labels":{"app":"auth-service"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","valueFrom":{"configMapKeyRef":{"key":"AUTH_DB_HOST","name":"app-config"}}},{"name":"DB_PORT","valueFrom":{"configMapKeyRef":{"key":"AUTH_DB_PORT","name":"app-config"}}},{"name":"DB_NAME","valueFrom":{"configMapKeyRef":{"key":"AUTH_DB_NAME","name":"app-config"}}},{"name":"DB_USER","value":"postgres"},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"DB_PASSWORD","name":"db-auth-credentials"}}}],"image":"905418203619.dkr.ecr.sa-east-1.amazonaws.com/auth-service:latest","imagePullPolicy":"IfNotPresent","name":"auth-service","ports":[{"containerPort":8001}],"resources":{"requests":{"cpu":"250m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2026-07-14T14:13:42Z"
  generation: 10
  labels:
    app: auth-service
  name: auth-service
  namespace: togglemaster
  resourceVersion: "44238"
  uid: 358a8846-2606-460f-aae7-a18779ba65b1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-07-14T13:16:35-03:00"
      labels:
        app: auth-service
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: AUTH_DB_HOST
              name: app-config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: AUTH_DB_PORT
              name: app-config
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: AUTH_DB_NAME
              name: app-config
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: db-auth-credentials
        image: 905418203619.dkr.ecr.sa-east-1.amazonaws.com/auth-service:latest
        imagePullPolicy: IfNotPresent
        name: auth-service
        ports:
        - containerPort: 8001
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2026-07-14T14:46:33Z"
    lastUpdateTime: "2026-07-14T16:15:23Z"
    message: ReplicaSet "auth-service-566d4bb67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-07-14T16:21:37Z"
    lastUpdateTime: "2026-07-14T16:21:37Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 10
  replicas: 2
  terminatingReplicas: 0
  unavailableReplicas: 2
  updatedReplicas: 2
