apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: togglemaster
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 905418203619.dkr.ecr.sa-east-1.amazonaws.com/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-auth-credentials
                  key: DATABASE_URL
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: db-auth-credentials
                  key: MASTER_KEY
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_DB_NAME
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-auth-credentials
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"