apiVersion: v1
kind: Secret
metadata:
  name: db-auth-credentials
  namespace: togglemaster
type: Opaque
data:
  DB_PASSWORD: cGxhY2Vob2xkZXI= # "postgres" em base64
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0B0b2dnbGVtYXN0ZXItYXV0aC1kYi5jeHdrcXl5eXc0eTMuc2EtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYXV0aF9kYg==
  MASTER_KEY: cGxhY2Vob2xkZXI=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-flag-credentials
  namespace: togglemaster
type: Opaque
data:
  DB_PASSWORD: cGxhY2Vob2xkZXI=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-targeting-credentials
  namespace: togglemaster
type: Opaque
data:
  DB_PASSWORD: cGxhY2Vob2xkZXI=
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster
type: Opaque
data:
  AWS_ACCESS_KEY_ID: REPLACE_WITH_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: REPLACE_WITH_AWS_SECRET_ACCESS_KEY