apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  selector:
    app: analytics-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
