apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: togglemaster
spec:
  selector:
    app: flag-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
